name: Update Changelog
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    name: Update Changelog
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
  
      - name: Set version environment variable
        run: |
          $tagName = "${{ github.event.release.tag_name }}"
          if (([string]::IsNullOrEmpty($tagName)))
          {
             $tagName = "${{ inputs.version }}"
          }
          # Check if the tag starts with 'v' and remove it
          if ($tagName.StartsWith("v")) {
              $version = $tagName.Substring(1)
          } else {
              $version = $tagName
          }
          
          Write-Host "The original tag name was: $tagName"
          Write-Host "The processed version is: $version"
          
          # Set the environment variable for subsequent steps in the same job
          echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "tagVersion=$tagName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh # Explicitly use PowerShell Core (default on windows-latest for 'run')
        
      - name: Generate changelog
        uses: bdashrad/git-chglog-action@v2.0.3
        with:
          git_chglog_version: 0.15.4
          tag: ..${{ env.tagVersion }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: master
          token: ${{ secrets.PR_SECRET }}
